version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # root of your project
    schedule:
      interval: "weekly" # or "daily", "monthly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "react"
        versions: ["18.x"]
