version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # location of your package.json
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
